### ISSUE TITLE
Add time duration in /unix-epoch

### ISSUE THREAD

**Issue by julesGoullee** [dl-solarity/frontend#52]
Timestamp and human date, are useful, in addition it will be nice to have converter for duration, like time in second to human readable duration in day, hours, second, eg: 
<img width="578" alt="Screenshot 2023-11-07 at 18 59 30" src="https://github.com/dl-solarity/frontend/assets/6892100/b244fa5c-95f6-4626-8a0e-c9291c8a792e">
(from https://www.epochconverter.com/)

**Comment by Arvolear** [comment]
Thank you for the idea! Will add that to the features list :)
